"""create contact requests table

Revision ID: 2f01d2119334
Revises: c9e49a723814
Create Date: 2026-07-02 01:40:13.378118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f01d2119334'
down_revision: Union[str, Sequence[str], None] = 'c9e49a723814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('budget_range_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_range_id'], ['budget_ranges.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_requests_budget_range_id'), 'contact_requests', ['budget_range_id'], unique=False)
    op.create_index(op.f('ix_contact_requests_id'), 'contact_requests', ['id'], unique=False)
    op.create_index(op.f('ix_contact_requests_lead_id'), 'contact_requests', ['lead_id'], unique=False)
    op.create_index(op.f('ix_contact_requests_service_id'), 'contact_requests', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_requests_service_id'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_lead_id'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_id'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_budget_range_id'), table_name='contact_requests')
    op.drop_table('contact_requests')
    # ### end Alembic commands ###
