"""add portfolio display fields

Revision ID: 55079e71d48f
Revises: ce3cef1f5f3a
Create Date: 2026-07-06 16:34:22.247317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55079e71d48f'
down_revision: Union[str, Sequence[str], None] = 'ce3cef1f5f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_projects', sa.Column('metric', sa.String(length=100), nullable=True))
    op.add_column('portfolio_projects', sa.Column('image_light_url', sa.String(length=500), nullable=True))
    op.add_column('portfolio_projects', sa.Column('image_dark_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_projects', 'image_dark_url')
    op.drop_column('portfolio_projects', 'image_light_url')
    op.drop_column('portfolio_projects', 'metric')
    # ### end Alembic commands ###
