"""update leads table

Revision ID: ed1eedbf0c51
Revises: 16fc6e80fe2c
Create Date: 2026-07-02 00:39:12.111405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1eedbf0c51'
down_revision: Union[str, Sequence[str], None] = '16fc6e80fe2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('status', sa.String(length=50), server_default=sa.text("'new'"), nullable=False))
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.drop_column('leads', 'updated_at')
    op.drop_column('leads', 'notes')
    op.drop_column('leads', 'status')
    # ### end Alembic commands ###
